name: Destroy AWS Infrastructure

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Confirm to destroy resources (yes/no)"
        required: true
        default: ""

permissions:
  contents: read

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Destroy Resources
        if: github.event.inputs.confirm == 'yes'
        working-directory: terraform
        run: |
          terraform destroy --target=module.route53.aws_route53_zone.zone --auto-approve
          terraform destroy --auto-approve

      - name: Check if all resources are destroyed
        if: github.event.inputs.confirm == 'yes'
        working-directory: terraform
        run: |
          remaining_resources=$(terraform state list)
          if [ -z "$remaining_resources" ]; then
            echo -e "\033[0;32m✔ All resources have been successfully destroyed!\033[0m"
          else
            echo -e "\033[0;31m❌ Some resources are still present in the Terraform state:\033[0m"
            echo "$remaining_resources"
            exit 1  # Exit with an error if there are still resources left
          fi
