name: Terraform ECR Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Create ECR"
        required: true
        default: "main"

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init
        working-directory: ./modules/ecr

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./modules/ecr
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
